### ISSUE TITLE
Keeping plugin up to date?

### ISSUE THREAD

**Issue by sdaitzman** [JohnCoates/CSSketch#1]
What's the best way to keep the plugin up to date?

**Comment by JohnCoates** [comment]
Great question! I'm looking to add it to http://sketchtoolbox.com/, I'll update this issue when that's done.

**Comment by sdaitzman** [comment]
cool, thanks :+1:

**Comment by benhinchley** [comment]
@JohnCoates Any progress on adding this to Sketch Toolbox?

**Comment by bomberstudios** [comment]
It's already there! : )

**Comment by JohnCoates** [comment]
@benhinchley as bomberstudios mentioned, it's available now on Sketch Toolbox.

Readme has been updated with this information
https://github.com/JohnCoates/CSSketch/commit/d30f286c70367676bb2988d05b0c2197d8b99226

**Comment by benhinchley** [comment]
:+1: thanks turned out was spelling it wrong
