### ISSUE TITLE
New Feature Request: .scss support

### ISSUE THREAD

**Issue by j-ordon** [JohnCoates/CSSketch#17]
I'd pay for it.

**Comment by olehmelnyk** [comment]
+1 for SASS/SCSS
or even pure css... so we would be able to write with our preferable CSS pre-/post- processors, then generate pure native .css file and attach it to Sketch layouts

**Comment by JohnCoates** [comment]
Ah, you'd pay for it? Well then... how much would you be willing to pay?

Just kidding, I just added it at no cost 😁

**Comment by JohnCoates** [comment]
@olehmelnyk pure CSS should have always been working, have you tried it?

**Comment by olehmelnyk** [comment]
@JohnCoates no, sorry, I'm just starting to learn Sketch and noticed that this plugin works with LESS, so I thought it's {less} only

if pure CSS is working then it's awesome! But I'm guessing that so far not all CSS properties/selectors works, just a few, am I right?

**Comment by JohnCoates** [comment]
@olehmelnyk No worries. 
Yes a lot of properties are missing currently. The supported ones can be found here: https://github.com/JohnCoates/CSSketch/blob/master/Readme.md#supported-css

I'm starting an iOS UX kit that I'll be building with CSSketch today, and I plan to add a lot more properties as I build it. Let me know if you have some requests and I'll try to get to them.

**Comment by olehmelnyk** [comment]
@JohnCoates  Great! Waiting for the update with new features support!

I don't have special requests for now, but it would be really great if in future we would be able to attach CSS file from bootstrap / material design / foundation / etc. and by giving proper class names to elements in Sketch get proper styling... I think it's doable but will take a lot of time to implement. But this would be the most epic and killer feature ever made for sure!!!
