### ISSUE TITLE
Provide detailed issue guidelines

### ISSUE THREAD

**Issue by clintonhalpin** [JohnCoates/CSSketch#2]
I'm having some trouble running this plugin. When I run `CSSketch > Layout Layers` or `CSSketch > Set Page's Stylesheet` it breaks the design pretty badly ( specifically on the example files ). Before I file any issues are there any tips on how to provide more detailed issues?

- Are there requirements for Mac / Sketch that you depend upon? 
- Is this plugin debuggable? How do I find the relevant debug logs to post more detailed issues?
- Anything else that would be useful?

**Comment by JohnCoates** [comment]
Thanks for the heads up!
Are you running El Capitan? Some of the example files use CSS properties that are only available in the latest version of WebKit. I'll update them shortly

The plugin is currently only debuggable only if you compile it in debug mode. Log is placed in ~/Documents/sketch.log

**Comment by clintonhalpin** [comment]
@JohnCoates I was running the plugin on Yosemite, so I guess that could be the issue ( read the docs :100: ). I haven't gotten to test this on El Capitan.

**Comment by JohnCoates** [comment]
@clintonhalpin I have updated the examples for Yosemite support if you want to give it another shot
