### ISSUE TITLE
missing bundle when trying to run? 

### ISSUE THREAD

**Issue by v3nt** [JohnCoates/CSSketch#20]
When trying to use new file of the examples

sketch Version 3.5.1 (25234).

**Comment by JohnCoates** [comment]
Did you use the installer, or did you double click the .sketchplugin file to install?

**Comment by v3nt** [comment]
hey John - i just loaded the plugin CSSketch.sketchplugin.  Is there something else that needs installing from the zip? Thanks, D.

**Comment by JohnCoates** [comment]
Could you try installing from the release https://github.com/JohnCoates/CSSketch/releases/latest

I've just switched CSSketch over to the [SketchKit](https://github.com/JohnCoates/SketchKit) framework, and it requires that be installed as well, so I wrote a little installer.

**Comment by v3nt** [comment]
that installer has done it! Thanks and looking forward to trying it out...

**Comment by krutynowski** [comment]
Hi, I have used Sketch Toolbox to install the plugin, followed by manual install. In all the cases I keep getting a missing bundle error.
I've tried to install on two separate machines one running ElCapitan and the other Sierra...
![screen shot 2017-01-19 at 11 06 54](https://cloud.githubusercontent.com/assets/16925945/22121120/7784fcb8-de37-11e6-8e52-b1294f5e0fa8.png)

**Comment by jamezilla0** [comment]
I got same issue

**Comment by saschaeggi** [comment]
Same issue here
