### ISSUE TITLE
Extending classes ain't working

### ISSUE THREAD

**Issue by pslanca** [JohnCoates/CSSketch#22]
![untitled](https://cloud.githubusercontent.com/assets/181502/13120124/2b7aa4cc-d5a4-11e5-85e0-7334dd094dfb.gif)
Seems that combining two or more classes on the layer name breaks the plugin.

Layer name example:
.className1 .className2

I'm using Sketch version 3.5.2 (25235)

**Comment by JohnCoates** [comment]
Could you post a .zip of your example so I can test it?

**Comment by pslanca** [comment]
@JohnCoates 
[Archive.zip](https://github.com/JohnCoates/CSSketch/files/136194/Archive.zip)

Thanks!

**Comment by pslanca** [comment]
@JohnCoates maybe this can help:
<img width="637" alt="screen shot 2016-02-21 at 21 55 44" src="https://cloud.githubusercontent.com/assets/181502/13205714/0a0d527c-d8e6-11e5-829c-74d9d2a757b4.png">

**Comment by JohnCoates** [comment]
Thanks @pslanca, the zip file and your console log have helped a lot.
I've fixed this bug and issued a new release.
https://github.com/JohnCoates/CSSketch/releases/latest
