### ISSUE TITLE
[idea] CSSketch reverse mode

### ISSUE THREAD

**Issue by darkdelphin** [JohnCoates/CSSketch#4]
Hi, John
Thanks for the awesome plugin.

Is it possible to to use Sketch api and webkit engine to work in "reverse mode"? I mean we give layers id/class-like names just like before and plugin generates CSS code based on styles that we apply to layers.
Something like capturing "Copy CSS Attributes" and outputting it in attached css file.

What do you think?

Thanks.

**Comment by JohnCoates** [comment]
That's actually a pretty cool idea! Unfortunately it's not relevant to my workflow right now, as I barely ever to any web development, so it doesn't interest me to develop it.

**Comment by darkdelphin** [comment]
Would you mind if I use your code to build upon it?

**Comment by JohnCoates** [comment]
Please do! I've licensed it under the MIT license, so you're free to build upon it, make whatever you want with it, use it commercially and closed source if you want. 😁

**Comment by darkdelphin** [comment]
Thanks, John. Good luck)
