### ISSUE TITLE
Does not work with Sketch 42

### ISSUE THREAD

**Issue by be-next-hotdog** [JohnCoates/CSSketch#57]
Hello, unfortunately, this plugin does work for me after successfully installing and setting stylesheet to my sample page. I tried to make a quick modification in css file but didn't find any change in sketch...

**Comment by nathanbiehl** [comment]
It hasn't worked since at least 3.9 for me. Appears to be an abandoned project at this point in time. :(

**Comment by guzforster** [comment]
In Sketch 43 when I try to create the page style sheet, it says that the "bundle" is missing from my computer. Don't know what that means.

**Comment by alecaro** [comment]
Can it be that doesn't work on Sketch 4? I'm trying to install it but it doesn't work.

**Comment by make-sum** [comment]
I loved this plugin. I was really hoping to see it continue.

**Comment by JohnCoates** [comment]
Sorry guys ☹️
