### ISSUE TITLE
Font-size support

### ISSUE THREAD

**Issue by kidcapricious** [JohnCoates/CSSketch#8]
Hey, John. This is amazing!

Will you be supporting font-sizes & other type related stuff like line-height, letter-spacing? Seems perfect for this.

Looks possible from peering through the code & checking Sketch's API's - beyond me, though! *_*

**Comment by tomrantala** [comment]
:+1:  for typography related stuff. If I could manage all my text styles trough CSS it would be so much better. It would revolutionize the workflow of Sketch design!

Where I can donate to you for this awesome plugin? :+1:

**Comment by tomrantala** [comment]
@JohnCoates what do you think about this feature?

**Comment by menosketiago** [comment]
:+1: on font-size and other font properties

but congrats on the plugin ;)

**Comment by JohnCoates** [comment]
Thanks for the feature request! I'll look into this feature.

Thanks for offering to donate @tomrantala, but I'm not currently accepting donations. Tweets are appreciated though 😁

**Comment by JohnCoates** [comment]
This has been added by @jleonard https://github.com/JohnCoates/CSSketch/pull/13
