### ISSUE TITLE
Crash if edited in Idea or Macvim

### ISSUE THREAD

**Issue by EuDgee** [JohnCoates/CSSketch#9]
Crashes Sketch if Less file edited in MacVim or IntelliJ Idea.
Crashes on file save. If edited in Sublime — everything works fine.

Crash dump for editing in Idea.
https://dl.dropboxusercontent.com/u/2262930/crash.log

**Comment by dev360** [comment]
Experienced the same with terminal vim.

**Comment by JohnCoates** [comment]
Fixed this issue in b3ca6701b353effe391c8b47e772480e3ceb1384 thanks for the bug report!
